name: Docker CI

on:
  push:
    branches:
      - master

env:
  GB_REGISTRY: ghcr.io
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Assign defaultValue
        run: |
          version=$(grep -m1 '^lichess_bot_version: ' lib/versioning.yml | sed -n -e 's/^.*://p' | tr -d '[:space:]')
          echo version="$version" >> "$GITHUB_ENV"
      
      - name: show me docker tags.
        run: |
          echo "version:'"$version"'"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Login to Github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GB_REGISTRY }}
          username: ${{ secrets.GB_REPO_USER }}
          password: ${{ secrets.GB_REPO_TOKEN }}
          
      - name: build and push fat image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_ORGANIZATION }}/${{ vars.DOCKER_IMG }}:latest
            ${{ vars.DOCKER_ORGANIZATION }}/${{ vars.DOCKER_IMG }}:${{ env.version }}
            ${{ env.GB_REGISTRY }}/${{ vars.DOCKER_ORGANIZATION }}/${{ vars.DOCKER_IMG }}:latest
            ${{ env.GB_REGISTRY }}/${{ vars.DOCKER_ORGANIZATION }}/${{ vars.DOCKER_IMG }}:${{ env.version }}

      - name: build and push alpine image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          build-args: VARIANT=-alpine
          push: true
          tags: |
            ${{ vars.DOCKER_ORGANIZATION }}/${{ vars.DOCKER_IMG }}:alpine
            ${{ vars.DOCKER_ORGANIZATION }}/${{ vars.DOCKER_IMG }}:${{ env.version }}-alpine
            ${{ env.GB_REGISTRY }}/${{ vars.DOCKER_ORGANIZATION }}/${{ vars.DOCKER_IMG }}:alpine
            ${{ env.GB_REGISTRY }}/${{ vars.DOCKER_ORGANIZATION }}/${{ vars.DOCKER_IMG }}:${{ env.version }}-alpine
