name: Versioning

on:
  push:
    branches: [ master ]

jobs:
  versioning:
      if: |
        !contains(github.event.head_commit.message, 'Auto update version') ||
        !contains(github.event.head_commit.message, 'Auto update wiki/Home.md')
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
      - name: Update version
        id: new-version
        run: python .github/workflows/update_version.py
      - name: Auto update version
        run: |
          git config --global user.email "123640915+Version-BOT@users.noreply.github.com"
          git config --global user.name "Version-BOT"
          git remote set-url origin ${{ secrets.version_bot_ssh }}
          git add versioning.yml
          git commit -m "Auto update version to ${{ steps.new-version.outputs.new_version }}"
          git push origin HEAD:master
